import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'es' | 'en' | 'de';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    es: {
        // Navbar
        'nav.home': 'Inicio',
        'nav.products': 'Productos',
        'nav.about': 'Nosotros',
        'nav.contact': 'Contacto',
        'nav.search': 'Buscar productos...',

        // Hero
        'hero.title1': 'COCHES',
        'hero.title1_alt': 'mejores.',
        'hero.title2': 'TALLERES',
        'hero.title2_alt': 'exitosos.',
        'hero.desc': 'Suministramos soluciones técnicas de alta gama exclusivamente para talleres especializados. Ingeniería alemana certificada para maximizar el rendimiento y la rentabilidad.',
        'hero.cta_products': 'Explorar Productos',
        'hero.cta_tech': 'Ver Tecnología',

        // Tech Section
        'tech.badge': 'Innovación Alemana',
        'tech.title': 'TECNOLOGÍA',
        'tech.title_alt': 'DE VANGUARDIA.',
        'tech.dct_title': 'Deposit Control Technology',
        'tech.dct_desc': 'La base de todos nuestros productos. Una fórmula molecular que desintegra depósitos sin dañar componentes sensibles.',
        'tech.power_title': 'Potencia Inmediata',
        'tech.power_desc': 'Resultados perceptibles desde los primeros kilómetros de uso.',
        'tech.shield_title': 'Protección Total',
        'tech.shield_desc': 'Certificación TUV que garantiza la seguridad de su motor.',
        'tech.gold_title': 'Estándar de Oro en Automoción',
        'tech.gold_desc': 'Utilizado por los principales fabricantes alemanes en sus programas de mantenimiento oficial.',
        'tech.more': 'Saber más',

        // About Section (Home)
        'about.badge': 'Nuestro Legado',
        'about.title': 'Hacemos que los coches',
        'about.title_alt': 'funcionen mejor.',
        'about.desc': 'Suministramos exclusivamente a talleres especializados desde hace más de 45 años. Basándonos en fórmulas probadas, producimos soluciones de alta calidad que optimizan la rentabilidad de su taller y la vida útil de cada vehículo.',
        'about.cat1': 'Motores & Transmisión',
        'about.cat2': 'Sistemas Térmicos',
        'about.cat3': 'Dinámica & Frenado',
        'about.cat4': 'Mantenimiento',
        'about.cat1.item1': 'Protección corrosión',
        'about.cat1.item2': 'Limpieza FAP',
        'about.cat2.item1': 'Sellado radiador',
        'about.cat2.item2': 'Aire acondicionado',
        'about.cat3.item1': 'Protección frenos',
        'about.cat3.item2': 'Caja dirección',
        'about.cat4.item1': 'Fórmulas DCT',
        'about.cat4.item2': 'Larga duración',
        'about.quote': '"Nuestros productos impulsan el éxito económico de nuestros clientes. Ofrecemos un concepto integral de consultoría y formación técnica avanzada."',
        'about.cta': 'Ver nuestra historia',
        'about.region1': 'Europa',
        'about.region2': 'Asia Oriental',
        'about.region3': 'Norte de África',

        // About Page (Full)
        'about_page.hero_badge': 'Pasión por el éxito',
        'about_page.hero_title': 'APOYANDO AL TALLER',
        'about_page.hero_title_alt': 'DESDE 1971.',
        'about_page.hero_desc': 'Hacer que los vehículos funcionen mejor y apoyar a los talleres en su éxito: nuestro objetivo durante más de 45 años.',
        'about_page.mission_badge': 'ADN Corporativo',
        'about_page.mission_title': 'EXPERTOS PARA',
        'about_page.mission_title_alt': 'PROFESIONALES.',
        'about_page.mission_desc': 'Nos ocupamos exclusivamente de productos técnicos y químicos para talleres especializados. Esta especialización nos ha convertido en verdaderos expertos en el campo de la automoción profesional.',
        'about_page.feature1_title': 'Empresa Familiar',
        'about_page.feature1_desc': 'El apellido Behrens es sinónimo de calidad, fiabilidad y pasión.',
        'about_page.feature2_title': 'Visión Global',
        'about_page.feature2_desc': 'Crecimiento constante en Europa, Asia Oriental y el Norte de África.',
        'about_page.feature3_title': 'Calidad Absoluta',
        'about_page.feature3_desc': 'Trabajamos exclusivamente con talleres independientes y concesionarios.',
        'about_page.feature4_title': 'Fabricado en Alemania',
        'about_page.feature4_desc': 'Todos nuestros productos se desarrollan y fabrican íntegramente en Alemania.',
        'about_page.goals_badge': 'Objetivos de Marca',
        'about_page.goals_title': 'La Receta del Éxito',
        'about_page.goal1_title': 'Innovación para Mecánicos',
        'about_page.goal1_desc': 'Productos innovadores de alta calidad diseñados por y para el profesional del automóvil.',
        'about_page.goal2_title': 'Valor Óptimo',
        'about_page.goal2_desc': 'Mantenemos una relación precio-rendimiento líder en el mercado internacional.',
        'about_page.goal3_title': 'Sostenibilidad Real',
        'about_page.goal3_desc': 'Desarrollo y distribución de productos respetuosos con el medio ambiente.',
        'about_page.goal4_title': 'Salud del Profesional',
        'about_page.goal4_desc': 'Evitamos el uso de materias primas tóxicas y cancerígenas para proteger la salud de los mecánicos.',
        'about_page.history_badge': 'Trayectoria Histórica',
        'about_page.history_title': 'NUESTRO',
        'about_page.history_title_alt': 'LEGADO.',
        'about_page.stat1_label': 'Experiencia',
        'about_page.stat1_sub': 'Años en el mercado',
        'about_page.stat2_label': 'Formación',
        'about_page.stat2_sub': 'Servicio técnico integral',
        'about_page.stat3_label': 'Soluciones',
        'about_page.stat3_sub': 'Tecnología de última generación',
        'about_page.presence_title': 'PRESENCIA EN MÁS DE',
        'about_page.presence_title_alt': '30 PAÍSES.',
        'about_page.final_quote': '"Ya sea mantenimiento, protección, limpieza, lubricación o unión: WEPP ofrece una calidad excepcional, asesoramiento especializado y un servicio integral para sus clientes."',
        'about_page.final_title': 'EL ÉXITO ES',
        'about_page.final_title_alt': 'CUESTIÓN DE CALIDAD.',
        'about_page.final_cta1': 'Contactar con Expertos',
        'about_page.final_cta2': 'Catálogo Profesional',

        // Timeline Data (ES)
        'timeline.1971.title': 'Fundación',
        'timeline.1971.desc': 'Knut Behrens funda una agencia de ventas de productos químico-técnicos en Aschaffenburg, Baviera. Introducción de aditivos profesionales para talleres.',
        'timeline.1974.title': 'Era TUNAP',
        'timeline.1974.desc': 'Socio fundador de TUNAP. Desarrollo de conceptos de marketing y expansión de la red de venta directa en Europa.',
        'timeline.1996.title': 'Nueva Etapa',
        'timeline.1996.desc': 'Knut Behrens abandona TUNAP tras 25 años para iniciar un proyecto independiente y familiar.',
        'timeline.1998.title': 'Nacimiento de WEPP',
        'timeline.1998.desc': 'Fundación de Werkstatt Profi Programm GmbH y registro mundial de la marca WEPP.',
        'timeline.1999.title': 'Expansión Benelux',
        'timeline.1999.desc': 'Distribución en Holanda, Bélgica, Luxemburgo y Gran Bretaña.',
        'timeline.2000.title': 'Regreso a Aschaffenburg',
        'timeline.2000.desc': 'La sede central de WEPP GmbH se traslada a su ciudad de origen.',
        'timeline.2003.title': 'Segunda Generación',
        'timeline.2003.desc': 'Tim Behrens se incorpora a WEPP GmbH, reforzando el carácter familiar.',
        'timeline.2007.title': 'Liderazgo Renovado',
        'timeline.2007.desc': 'Tim Behrens es nombrado Director General. Operaciones en Polonia.',
        'timeline.2010.title': 'Automechanika',
        'timeline.2010.desc': 'Expansión a Grecia y Balcanes.',
        'timeline.2012.title': 'Innovación DPF',
        'timeline.2012.desc': 'Presentación del sistema de limpieza de filtros de partículas (DPF).',
        'timeline.2014.title': 'Certificación TÜV',
        'timeline.2014.desc': 'TÜV Thüringen certifica la eficacia de WEPP 2032 y 2036.',
        'timeline.2015.title': 'Nueva Sede',
        'timeline.2015.desc': 'Mudanza a Großenlüder-Bimbach. Expansión a Marruecos.',
        'timeline.2016.title': 'Homologación BMW',
        'timeline.2016.desc': 'Listado oficial del limpiador DPF en BMW.',
        'timeline.2018.title': 'Presencia Global',
        'timeline.2018.desc': 'Nuevos socios en Indonesia, Irak, Tanzania y Kazajistán.',
        'timeline.2024.title': 'WEPP España',
        'timeline.2024.desc': 'Consolidación en España a través de Michael Leffler.',

        // Workshop Section
        'workshop.badge': 'Red de Talleres',
        'workshop.title': '¿ERES UN TALLER PROFESIONAL?',
        'workshop.desc': 'Únete a la red oficial gestionada por Michael Leffler en España. Accede a formación técnica avanzada, herramientas de diagnóstico DCT y soporte directo de importación.',
        'workshop.cta1': 'Registrar Taller',
        'workshop.cta2': 'Soporte Técnico',

        // AI Advisor
        'advisor.badge': 'Diagnóstico Inteligente DCT',
        'advisor.title': 'SOPORTE',
        'advisor.title_alt': 'EN TIEMPO REAL.',
        'advisor.desc': 'Nuestra IA ha sido entrenada con décadas de experiencia en ingeniería química alemana para ofrecerle la solución exacta a cualquier problema de rendimiento.',
        'advisor.feat1_title': 'Precisión Certificada',
        'advisor.feat1_desc': 'Recomendaciones basadas en protocolos oficiales.',
        'advisor.feat2_title': 'Base de Datos Global',
        'advisor.feat2_desc': 'Acceso a miles de casos de éxito en talleres.',
        'advisor.welcome': '¡Bienvenido al Centro de Diagnóstico WEPP! Soy su asesor técnico inteligente. Por favor, describa los síntomas de su vehículo o el mantenimiento que desea realizar.',
        'advisor.error': 'Lo siento, ha ocurrido un error en la conexión con el servidor de diagnóstico. Por favor, inténtelo de nuevo.',
        'advisor.processing': 'Procesando',
        'advisor.placeholder': 'Describa el síntoma o mantenimiento...',

        // Product Categories
        'cat.motor': 'Motor y Transmisión',
        'cat.cooling': 'Refrigeración',
        'cat.ac': 'Aire Acondicionado',
        'cat.fuel': 'Combustible',
        'cat.brakes': 'Frenos',
        'cat.maintenance': 'Mantenimiento y Cuidado',
        'cat.body': 'Carrocería',

        // Product Card
        'product.specs': 'Especificaciones',
        'product.tech_sheet': 'Ficha Técnica',
        'product.ref': 'Referencia',
        'product.view_details': 'Ver Detalles',

        // Products View
        'products.badge': 'Catálogo Oficial',
        'products.title': 'NUESTROS',
        'products.title_alt': 'productos.',
        'products.cat_all': 'Todos',

        // Footer
        'footer.brand_desc': 'Líderes mundiales en ingeniería química para automoción. Tecnología alemana aplicada al mantenimiento profesional.',
        'footer.official_provider': 'Proveedor Oficial',
        'footer.legal': 'Aviso Legal',
        'footer.privacy': 'Privacidad',
        'footer.cookies': 'Cookies',

        // Contact
        'contact.badge': 'Canal Directo',
        'contact.title': 'ESTEMOS EN',
        'contact.title_alt': 'contacto.',
        'contact.desc': '¿Tiene alguna duda técnica sobre nuestros productos o está interesado en unirse a nuestra red oficial de talleres? Nuestro equipo coordinado por Michael Leffler gestionará su solicitud a la mayor brevedad.',
        'contact.form_title': 'Formulario de Consulta',
        'contact.form_required': 'Todos los campos son obligatorios',
        'contact.label_salutation': 'Tratamiento',
        'contact.label_name': 'Nombre Completo',
        'contact.label_email': 'Email de Contacto',
        'contact.label_message': 'Mensaje o Consulta',
        'contact.placeholder_name': 'ej. Juan Pérez',
        'contact.placeholder_email': 'ej. taller@profesional.es',
        'contact.placeholder_message': '¿En qué podemos ayudarle?',
        'contact.submit': 'ENVIAR SOLICITUD',
        'contact.sending': 'ENVIANDO...',
        'contact.sent': '¡MENSAJE ENVIADO!',
        'contact.privacy': 'Al enviar, acepta nuestra política de privacidad y protección de datos.',
        'contact.email_label': 'Email Profesional',
        'contact.phone_label': 'Soporte Directo',
        'contact.footer_note': 'WEPP GERMANY · INNOVACIÓN QUÍMICA DESDE 1980',
        'contact.salutation_mr': 'Sr.',
        'contact.salutation_ms': 'Sra.',
        'contact.salutation_company': 'Empresa'
    },
    en: {
        'nav.home': 'Home',
        'nav.products': 'Products',
        'nav.about': 'About Us',
        'nav.contact': 'Contact',
        'nav.search': 'Search products...',
        'hero.title1': 'BETTER',
        'hero.title1_alt': 'cars.',
        'hero.title2': 'SUCCESSFUL',
        'hero.title2_alt': 'workshops.',
        'hero.desc': 'We supply high-end technical solutions exclusively for specialized workshops. Certified German engineering to maximize performance and profitability.',
        'hero.cta_products': 'Explore Products',
        'hero.cta_tech': 'View Technology',
        'tech.badge': 'German Innovation',
        'tech.title': 'CUTTING-EDGE',
        'tech.title_alt': 'TECHNOLOGY.',
        'tech.dct_title': 'Deposit Control Technology',
        'tech.dct_desc': 'The foundation of all our products. A molecular formula that disintegrates deposits without damaging sensitive components.',
        'tech.power_title': 'Immediate Power',
        'tech.power_desc': 'Noticeable results from the first kilometers of use.',
        'tech.shield_title': 'Total Protection',
        'tech.shield_desc': 'TUV certification ensuring your engine\'s safety.',
        'tech.gold_title': 'Automotive Gold Standard',
        'tech.gold_desc': 'Used by leading German manufacturers in their official maintenance programs.',
        'tech.more': 'Learn more',
        'about.badge': 'Our Legacy',
        'about.title': 'We make cars',
        'about.title_alt': 'run better.',
        'about.desc': 'We have been supplying exclusively to specialized workshops for over 45 years. Based on proven formulas, we produce high-quality solutions that optimize workshop profitability and vehicle lifespan.',
        'about.cat1': 'Engine & Transmission',
        'about.cat2': 'Thermal Systems',
        'about.cat3': 'Dynamics & Braking',
        'about.cat4': 'Maintenance',
        'about.cat1.item1': 'Corrosion protection',
        'about.cat1.item2': 'DPF cleaning',
        'about.cat2.item1': 'Radiator sealing',
        'about.cat2.item2': 'Air conditioning',
        'about.cat3.item1': 'Brake protection',
        'about.cat3.item2': 'Steering box',
        'about.cat4.item1': 'DCT Formulas',
        'about.cat4.item2': 'Long duration',
        'about.quote': '"Our products drive the economic success of our customers. We offer a comprehensive concept of consulting and advanced technical training."',
        'about.cta': 'See our story',
        'about.region1': 'Europe',
        'about.region2': 'East Asia',
        'about.region3': 'North Africa',
        'about_page.hero_badge': 'Passion for success',
        'about_page.hero_title': 'SUPPORTING WORKSHOPS',
        'about_page.hero_title_alt': 'SINCE 1971.',
        'about_page.hero_desc': 'Making vehicles run better and supporting workshops in their success: our goal for over 45 years.',
        'about_page.mission_badge': 'Corporate DNA',
        'about_page.mission_title': 'EXPERTS FOR',
        'about_page.mission_title_alt': 'PROFESSIONALS.',
        'about_page.mission_desc': 'We deal exclusively with technical and chemical products for specialized workshops. This specialization has made us true experts in the professional automotive field.',
        'about_page.feature1_title': 'Family Company',
        'about_page.feature1_desc': 'The Behrens name stands for quality, reliability, and passion.',
        'about_page.feature2_title': 'Global Vision',
        'about_page.feature2_desc': 'Constant growth in Europe, East Asia, and North Africa.',
        'about_page.feature3_title': 'Absolute Quality',
        'about_page.feature3_desc': 'We work exclusively with independent workshops and dealerships.',
        'about_page.feature4_title': 'Made in Germany',
        'about_page.feature4_desc': 'All our products are developed and manufactured entirely in Germany.',
        'about_page.goals_badge': 'Brand Goals',
        'about_page.goals_title': 'The Recipe for Success',
        'about_page.goal1_title': 'Innovation for Mechanics',
        'about_page.goal1_desc': 'High-quality innovative products designed by and for the automotive professional.',
        'about_page.goal2_title': 'Optimal Value',
        'about_page.goal2_desc': 'We maintain a leading price-performance ratio in the international market.',
        'about_page.goal3_title': 'Real Sustainability',
        'about_page.goal3_desc': 'Development and distribution of environmentally friendly products.',
        'about_page.goal4_title': 'Professional Health',
        'about_page.goal4_desc': 'We avoid the use of toxic and carcinogenic raw materials to protect mechanics\' health.',
        'about_page.history_badge': 'Historical Trajectory',
        'about_page.history_title': 'OUR',
        'about_page.history_title_alt': 'LEGACY.',
        'about_page.stat1_label': 'Experience',
        'about_page.stat1_sub': 'Years in market',
        'about_page.stat2_label': 'Training',
        'about_page.stat2_sub': 'Full technical service',
        'about_page.stat3_label': 'Solutions',
        'about_page.stat3_sub': 'Next-gen technology',
        'about_page.presence_title': 'PRESENCE IN OVER',
        'about_page.presence_title_alt': '30 COUNTRIES.',
        'about_page.final_quote': '"Whether it is maintenance, protection, cleaning, lubrication, or bonding: WEPP offers exceptional quality, expert advice, and comprehensive service for its customers."',
        'about_page.final_title': 'SUCCESS IS',
        'about_page.final_title_alt': 'A MATTER OF QUALITY.',
        'about_page.final_cta1': 'Contact Experts',
        'about_page.final_cta2': 'Professional Catalog',
        'timeline.1971.title': 'Founding',
        'timeline.1971.desc': 'Knut Behrens founds a sales agency for chemical-technical products in Aschaffenburg, Bavaria. Introduction of professional additives.',
        'timeline.1974.title': 'TUNAP Era',
        'timeline.1974.desc': 'Founding partner of TUNAP. Development of marketing concepts and expansion in Europe.',
        'timeline.1996.title': 'New Stage',
        'timeline.1996.desc': 'Knut Behrens leaves TUNAP after 25 years to start an independent family project.',
        'timeline.1998.title': 'Birth of WEPP',
        'timeline.1998.desc': 'Foundation of Werkstatt Profi Programm GmbH and global registration of the WEPP brand.',
        'timeline.1999.title': 'Benelux Expansion',
        'timeline.1999.desc': 'Distribution in Netherlands, Belgium, Luxembourg, and Great Britain.',
        'timeline.2000.title': 'Return to Aschaffenburg',
        'timeline.2000.desc': 'WEPP GmbH headquarters move back to their home city.',
        'timeline.2003.title': 'Second Generation',
        'timeline.2003.desc': 'Tim Behrens joins WEPP GmbH, reinforcing the family character.',
        'timeline.2007.title': 'Renewed Leadership',
        'timeline.2007.desc': 'Tim Behrens appointed Managing Director. Operations in Poland.',
        'timeline.2010.title': 'Automechanika',
        'timeline.2010.desc': 'Expansion to Greece and Balkans.',
        'timeline.2012.title': 'DPF Innovation',
        'timeline.2012.desc': 'Presentation of the particulate filter (DPF) cleaning system.',
        'timeline.2014.title': 'TÜV Certification',
        'timeline.2014.desc': 'TÜV Thüringen certifies the efficacy of WEPP 2032 and 2036.',
        'timeline.2015.title': 'New Headquarters',
        'timeline.2015.desc': 'Move to Großenlüder-Bimbach facilities. Expansion to Morocco.',
        'timeline.2016.title': 'BMW Approval',
        'timeline.2016.desc': 'Official listing of DPF cleaner in BMW.',
        'timeline.2018.title': 'Global Presence',
        'timeline.2018.desc': 'New partners in Indonesia, Iraq, Tanzania, and Kazakhstan.',
        'timeline.2024.title': 'WEPP Spain',
        'timeline.2024.desc': 'Consolidation in Spain through Michael Leffler.',
        'workshop.badge': 'Workshop Network',
        'workshop.title': 'ARE YOU A PROFESSIONAL WORKSHOP?',
        'workshop.desc': 'Join the official network managed by Michael Leffler in Spain. Access advanced technical training, DCT diagnostic tools, and direct import support.',
        'workshop.cta1': 'Register Workshop',
        'workshop.cta2': 'Technical Support',
        'advisor.badge': 'DCT Intelligent Diagnosis',
        'advisor.title': 'REAL-TIME',
        'advisor.title_alt': 'SUPPORT.',
        'advisor.desc': 'Our AI has been trained with decades of German chemical engineering experience to offer the exact solution to any performance issue.',
        'advisor.feat1_title': 'Certified Precision',
        'advisor.feat1_desc': 'Recommendations based on official protocols.',
        'advisor.feat2_title': 'Global Database',
        'advisor.feat2_desc': 'Access to thousands of workshop success cases.',
        'advisor.welcome': 'Welcome to the WEPP Diagnostic Center! I am your intelligent technical advisor. Please describe your vehicle symptoms or desired maintenance.',
        'advisor.error': 'Sorry, an error occurred in the connection with the diagnostic server. Please try again.',
        'advisor.processing': 'Processing',
        'advisor.placeholder': 'Describe symptom or maintenance...',
        'cat.motor': 'Engine & Transmission',
        'cat.cooling': 'Cooling',
        'cat.ac': 'Air Conditioning',
        'cat.fuel': 'Fuel',
        'cat.brakes': 'Brakes',
        'cat.maintenance': 'Maintenance & Care',
        'cat.body': 'Bodywork',
        'product.specs': 'Specifications',
        'product.tech_sheet': 'Technical Sheet',
        'product.ref': 'Reference',
        'product.view_details': 'View Details',
        'contact.badge': 'Direct Channel',
        'contact.title': 'GET IN',
        'contact.title_alt': 'touch.',
        'contact.desc': 'Do you have a technical question about our products or are you interested in joining our official workshop network? Our team coordinated by Michael Leffler will process your request as soon as possible.',
        'contact.form_title': 'Inquiry Form',
        'contact.form_required': 'All fields are required',
        'contact.label_salutation': 'Salutation',
        'contact.label_name': 'Full Name',
        'contact.label_email': 'Contact Email',
        'contact.label_message': 'Message or Inquiry',
        'contact.placeholder_name': 'e.g. John Doe',
        'contact.placeholder_email': 'e.g. workshop@professional.com',
        'contact.placeholder_message': 'How can we help you?',
        'contact.submit': 'SEND REQUEST',
        'contact.sending': 'SENDING...',
        'contact.sent': 'MESSAGE SENT!',
        'contact.privacy': 'By sending, you accept our privacy policy and data protection.',
        'contact.email_label': 'Professional Email',
        'contact.phone_label': 'Direct Support',
        'contact.footer_note': 'WEPP GERMANY · CHEMICAL INNOVATION SINCE 1980',
        'contact.salutation_mr': 'Mr.',
        'contact.salutation_ms': 'Ms.',
        'contact.salutation_company': 'Company',
        'products.badge': 'Official Catalog',
        'products.title': 'OUR',
        'products.title_alt': 'products.',
        'products.cat_all': 'All',
        'footer.brand_desc': 'Global leaders in chemical engineering for automotive. German technology applied to professional maintenance.',
        'footer.official_provider': 'Official Provider',
        'footer.legal': 'Legal Notice',
        'footer.privacy': 'Privacy',
        'footer.cookies': 'Cookies'
    },
    de: {
        'nav.home': 'Startseite',
        'nav.products': 'Produkte',
        'nav.about': 'Über uns',
        'nav.contact': 'Kontakt',
        'nav.search': 'Produkte suchen...',
        'hero.title1': 'BESSERE',
        'hero.title1_alt': 'autos.',
        'hero.title2': 'ERFOLGREICHE',
        'hero.title2_alt': 'werkstätten.',
        'hero.desc': 'Wir liefern High-End-Technische Lösungen exklusiv für Fachwerkstätten. Zertifizierte deutsche Ingenieurskunst zur Maximierung von Leistung und Rentabilität.',
        'hero.cta_products': 'Produkte entdecken',
        'hero.cta_tech': 'Technologie ansehen',
        'tech.badge': 'Deutsche Innovation',
        'tech.title': 'ZUKUNFTSWEISENDE',
        'tech.title_alt': 'TECHNOLOGIE.',
        'tech.dct_title': 'Deposit Control Technology',
        'tech.dct_desc': 'Die Basis all unserer Produkte. Eine Molekularformel, die Ablagerungen auflöst, ohne empfindliche Komponenten zu beschädigen.',
        'tech.power_title': 'Sofortige Leistung',
        'tech.power_desc': 'Spürbare Ergebnisse ab den ersten Kilometern.',
        'tech.shield_title': 'Totaler Schutz',
        'tech.shield_desc': 'TÜV-Zertifizierung garantiert die Sicherheit Ihres Motors.',
        'tech.gold_title': 'Goldstandard der Automobilindustrie',
        'tech.gold_desc': 'Eingesetzt von führenden deutschen Herstellern in ihren offiziellen Wartungsprogrammen.',
        'tech.more': 'Mehr erfahren',
        'about.badge': 'Unser Erbe',
        'about.title': 'Wir machen Autos',
        'about.title_alt': 'besser.',
        'about.desc': 'Seit over 45 Jahren beliefern wir ausschließlich Fachwerkstätten. Basierend auf bewährten Formeln produzieren wir hochwertige Lösungen, die die Wirtschaftlichkeit Ihrer Werkstatt und die Lebensdauer jedes Fahrzeugs optimieren.',
        'about.cat1': 'Motor & Getriebe',
        'about.cat2': 'Thermische Systeme',
        'about.cat3': 'Dynamik & Bremsen',
        'about.cat4': 'Wartung',
        'about.cat1.item1': 'Korrosionsschutz',
        'about.cat1.item2': 'DPF-Reinigung',
        'about.cat2.item1': 'Kühlerdicht',
        'about.cat2.item2': 'Klimaanlage',
        'about.cat3.item1': 'Bremsenschutz',
        'about.cat3.item2': 'Lenkgetriebe',
        'about.cat4.item1': 'DCT-Formeln',
        'about.cat4.item2': 'Lange Lebensdauer',
        'about.quote': '"Unsere Produkte treiben den wirtschaftlichen Erfolg unserer Kunden voran. Wir bieten ein ganzheitliches Konzept aus Beratung und fortgeschrittener technischer Schulung."',
        'about.cta': 'Unsere Geschichte',
        'about.region1': 'Europa',
        'about.region2': 'Ostasien',
        'about.region3': 'Nordafrika',
        'about_page.hero_badge': 'Leidenschaft für Erfolg',
        'about_page.hero_title': 'UNTERSTÜTZUNG FÜR WERKSTÄTTEN',
        'about_page.hero_title_alt': 'SEIT 1971.',
        'about_page.hero_desc': 'Fahrzeuge besser laufen lassen und Werkstätten in ihrem Erfolg unterstützen: unser Ziel seit über 45 Jahren.',
        'about_page.mission_badge': 'Unternehmens-DNA',
        'about_page.mission_title': 'EXPERTEN FÜR',
        'about_page.mission_title_alt': 'PROFIS.',
        'about_page.mission_desc': 'Wir beschäftigen uns ausschließlich mit technischen und chemischen Produkten für Fachwerkstätten. Diese Spezialisierung hat uns zu Experten im professionellen Automobilbereich gemacht.',
        'about_page.feature1_title': 'Familienunternehmen',
        'about_page.feature1_desc': 'Der Name Behrens steht für Qualität, Zuverlässigkeit und Leidenschaft.',
        'about_page.feature2_title': 'Globale Vision',
        'about_page.feature2_desc': 'Stetiges Wachstum in Europa, Ostasien und Nordafrika.',
        'about_page.feature3_title': 'Absolute Qualität',
        'about_page.feature3_desc': 'Wir arbeiten ausschließlich mit freien Werkstätten und Autohäusern.',
        'about_page.feature4_title': 'Hergestellt in Deutschland',
        'about_page.feature4_desc': 'Alle unsere Produkte werden vollständig in Deutschland entwickelt und hergestellt.',
        'about_page.goals_badge': 'Markenziele',
        'about_page.goals_title': 'Das Erfolgsrezept',
        'about_page.goal1_title': 'Innovation für Mechaniker',
        'about_page.goal1_desc': 'Hochwertige innovative Produkte, entworfen von und für Automobilprofis.',
        'about_page.goal2_title': 'Optimaler Wert',
        'about_page.goal2_desc': 'Wir halten ein führendes Preis-Leistungs-Verhältnis auf dem internationalen Markt.',
        'about_page.goal3_title': 'Echte Nachhaltigkeit',
        'about_page.goal3_desc': 'Entwicklung und Vertrieb von umweltfreundlichen Produkten.',
        'about_page.goal4_title': 'Berufsgesundheit',
        'about_page.goal4_desc': 'Wir vermeiden den Einsatz von giftigen und krebserregenden Rohstoffen.',
        'about_page.history_badge': 'Historischer Werdegang',
        'about_page.history_title': 'UNSER',
        'about_page.history_title_alt': 'ERBE.',
        'about_page.stat1_label': 'Erfahrung',
        'about_page.stat1_sub': 'Jahre am Markt',
        'about_page.stat2_label': 'Schulung',
        'about_page.stat2_sub': 'Full Technical Service',
        'about_page.stat3_label': 'Lösungen',
        'about_page.stat3_sub': 'Modernste Technologie',
        'about_page.presence_title': 'PRÄZENZ IN ÜBER',
        'about_page.presence_title_alt': '30 LÄNDERN.',
        'about_page.final_quote': '"Ob Wartung, Schutz, Reinigung, Schmierung oder Verbindung: WEPP bietet außergewöhnliche Qualität, kompetente Beratung und umfassenden Service."',
        'about_page.final_title': 'ERFOLG IST',
        'about_page.final_title_alt': 'QUALITÄTSSACHE.',
        'about_page.final_cta1': 'Experten kontaktieren',
        'about_page.final_cta2': 'Profi-Katalog',
        'timeline.1971.title': 'Gründung',
        'timeline.1971.desc': 'Knut Behrens gründet eine Verkaufsagentur für chemisch-technische Produkte in Aschaffenburg, Bayern.',
        'timeline.1974.title': 'TUNAP Ära',
        'timeline.1974.desc': 'Gründungspartner von TUNAP. Entwicklung von Marketingkonzepten und Expansion in Europa.',
        'timeline.1996.title': 'Neue Etappe',
        'timeline.1996.desc': 'Knut Behrens verlässt TUNAP nach 25 Jahren für ein unabhängiges Familienprojekt.',
        'timeline.1998.title': 'Geburt von WEPP',
        'timeline.1998.desc': 'Gründung der Werkstatt Profi Programm GmbH und weltweite Eintragung der Marke WEPP.',
        'timeline.1999.title': 'Benelux Expansion',
        'timeline.1999.desc': 'Vertrieb in Holland, Belgien, Luxemburg und Großbritannien.',
        'timeline.2000.title': 'Rückkehr nach Aschaffenburg',
        'timeline.2000.desc': 'Hauptsitz der WEPP GmbH zieht zurück in die Heimatstadt.',
        'timeline.2003.title': 'Zweite Generation',
        'timeline.2003.desc': 'Tim Behrens tritt in die WEPP GmbH ein, stärkt den Familiencharakter.',
        'timeline.2007.title': 'Erneuerte Führung',
        'timeline.2007.desc': 'Tim Behrens wird zum Geschäftsführer ernannt. Operationen in Polen.',
        'timeline.2010.title': 'Automechanika',
        'timeline.2010.desc': 'Expansion nach Griechenland und auf den Balkan.',
        'timeline.2012.title': 'DPF Innovation',
        'timeline.2012.desc': 'Vorstellung des DPF-Reinigungssystems.',
        'timeline.2014.title': 'TÜV-Zertifizierung',
        'timeline.2014.desc': 'TÜV Thüringen zertifiziert die Wirksamkeit von WEPP 2032 und 2036.',
        'timeline.2015.title': 'Neuer Hauptsitz',
        'timeline.2015.desc': 'Umzug nach Großenlüder-Bimbach facilities. Expansion nach Marokko.',
        'timeline.2016.title': 'BMW-Freigabe',
        'timeline.2016.desc': 'Offizielle Listung des DPF-Reinigers bei BMW.',
        'timeline.2018.title': 'Globale Präsenz',
        'timeline.2018.desc': 'Neue Partner in Indonesien, Irak, Tansania und Kasachstan.',
        'timeline.2024.title': 'WEPP Spanien',
        'timeline.2024.desc': 'Konsoliderung in Spanien durch Michael Leffler.',
        'workshop.badge': 'Werkstattnetzwerk',
        'workshop.title': 'SIND SIE EINE FACHWERKSTATT?',
        'workshop.desc': 'Werden Sie Teil des offiziellen Netzwerks, das von Michael Leffler in Spanien verwaltet wird. Erhalten Sie Zugang zu fortgeschrittenen technischen Schulungen, DCT-Diagnosetools und direkter Importunterstützung.',
        'workshop.cta1': 'Werkstatt registrieren',
        'workshop.cta2': 'Technischer Support',
        'advisor.badge': 'DCT Intelligente Diagnose',
        'advisor.title': 'ECHTZEIT',
        'advisor.title_alt': 'SUPPORT.',
        'advisor.desc': 'Unsere KI wurde mit jahrzehntelanger deutscher Chemie-Expertise trainiert, um die exakte Lösung für jedes Leistungsproblem zu bieten.',
        'advisor.feat1_title': 'Zertifizierte Präzision',
        'advisor.feat1_desc': 'Empfehlungen basierend auf offiziellen Protokollen.',
        'advisor.feat2_title': 'Globale Datenbank',
        'advisor.feat2_desc': 'Zugriff auf Tausende von Werkstatt-Erfolgsfällen.',
        'advisor.welcome': 'Willkommen im WEPP-Diagnosezentrum! Ich bin Ihr intelligenter technischer Berater. Bitte beschreiben Sie Ihre Fahrzeugsymptome oder die gewünschte Wartung.',
        'advisor.error': 'Entschuldigung, bei der Verbindung mit dem Diagnoseserver ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut.',
        'advisor.processing': 'Verarbeitung',
        'advisor.placeholder': 'Symptom oder Wartung beschreiben...',
        'cat.motor': 'Motor & Getriebe',
        'cat.cooling': 'Kühlung',
        'cat.ac': 'Klimaanlage',
        'cat.fuel': 'Kraftstoff',
        'cat.brakes': 'Bremsen',
        'cat.maintenance': 'Wartung & Pflege',
        'cat.body': 'Karosserie',
        'product.specs': 'Spezifikationen',
        'product.tech_sheet': 'Technisches Datenblatt',
        'product.ref': 'Referenz',
        'product.view_details': 'Details anzeigen',
        'contact.badge': 'Direkter Kanal',
        'contact.title': 'NEHMEN SIE',
        'contact.title_alt': 'kontakt auf.',
        'contact.desc': 'Haben Sie eine technische Frage zu unseren Produkten o. sind Sie daran interessiert, unserem offiziellen Werkstattnetzwerk beizutreten? Unser Team unter Michael Leffler wird Ihre Anfrage schnellstmöglich bearbeiten.',
        'contact.form_title': 'Anfrageformular',
        'contact.form_required': 'Alle Felder sind Pflichtfelder',
        'contact.label_salutation': 'Anrede',
        'contact.label_name': 'Vollständiger Name',
        'contact.label_email': 'Kontakt-E-Mail',
        'contact.label_message': 'Nachricht oder Anfrage',
        'contact.placeholder_name': 'z.B. Max Mustermann',
        'contact.placeholder_email': 'z.B. werkstatt@profi.de',
        'contact.placeholder_message': 'Wie können wir Ihnen helfen?',
        'contact.submit': 'ANFRAGE SENDEN',
        'contact.sending': 'SENDEN...',
        'contact.sent': 'NACHRICHT GESENDET!',
        'contact.privacy': 'Mit dem Absenden akzeptieren Sie unsere Datenschutzbestimmungen.',
        'contact.email_label': 'Professionelle E-Mail',
        'contact.phone_label': 'Direkter Support',
        'contact.footer_note': 'WEPP GERMANY · CHEMISCHE INNOVATION SEIT 1980',
        'contact.salutation_mr': 'Hr.',
        'contact.salutation_ms': 'Fr.',
        'contact.salutation_company': 'Firma',
        'products.badge': 'Offizieller Katalog',
        'products.title': 'UNSERE',
        'products.title_alt': 'produkte.',
        'products.cat_all': 'Alle',
        'footer.brand_desc': 'Weltweit führend in chemischer Technik für die Automobilindustrie. Deutsche Technologie für professionelle Wartung.',
        'footer.official_provider': 'Offizieller Anbieter',
        'footer.legal': 'Impressum',
        'footer.privacy': 'Datenschutz',
        'footer.cookies': 'Cookies'
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
    const [language, setLanguage] = useState<Language>('es');

    const t = (key: string) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
